server: https://chat.internal.service.toshi.org
token_ethereum_service_url: https://ethereum.internal.service.toshi.org
token_id_service_url: https://identity.internal.service.toshi.org
token_exchange_service_url: https://exchange.internal.service.toshi.org
redis:
  envKey: REDIS_URL
  timeout: 2000
storage:
  envKey: DATABASE_URL
  sslmode: disable
